### ISSUE TITLE
Add Doctrine2 Cookbook

### ISSUE THREAD

**Issue by bshaffer** [bshaffer/oauth2-server-php-docs#2]
Add a Doctrine2 article to the cookbook

**Comment by kusmierz** [comment]
@bshaffer is there any example/cookbook/tips to integrate oauth2-server and doctrine2?

**Comment by bshaffer** [comment]
Yes! See the following:

config files: https://github.com/bshaffer/oauth2-server-bundle/tree/develop/Resources/config/doctrine
entity files: https://github.com/bshaffer/oauth2-server-bundle/tree/develop/Entity

It's part of the symfony2 bundle, so it's not as agnostic as I would like it, but if you're familiar with Doctrine2 it's a good place to start

**Comment by kusmierz** [comment]
Thanks @bshaffer indeed, I've written Doctrine Adapter and it wasn't too hard :)

Anyway - is there any _actual_ db struct? I've found at least 3, all different between each other.

**Comment by bshaffer** [comment]
see "Define your Schema" on the [Step-by-Step Walkthrough](http://bshaffer.github.io/oauth2-server-php-docs/cookbook/).  Is this what you're looking for?

**Comment by kusmierz** [comment]
part of...

See ie.: https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L518-524 there is jti table, what is for?

In schema above, user has only username, password, first and lastname, but here: https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php#L501-503 email address and scope also.

Which is correct?

**Comment by bshaffer** [comment]
The differences depend on what grant types you implement, and whether you use OpenID Connect. If you're using the `JWTBearer` grant type, *and* you are supporting `jti` (which is optional), you'll want the JTI table. If you're using OpenIDConnect AND you want to support the `email_address` claim, you'll want to have those fields as part of your user storage.

I wouldn't worry about it... most of those fields/tables are optional, and it doesn't sound like your implementation will need them.

**Comment by kusmierz** [comment]
Now I understand, thanks. Is there anywhere described all of those "optional" fields?
