### ISSUE TITLE
JWT scope attributes should be separated by space

### ISSUE THREAD

**Issue by jonnybbb** [bshaffer/oauth2-server-php-docs#65]
According to the [JWT OAuth2 spec](http://tools.ietf.org/html/rfc6749#appendix-A.4) the scope attribute is a list of space separated values, instead of comma as mentioned in the [docs](https://github.com/bshaffer/oauth2-server-php-docs/blob/ef1786ff2ad84d9f4d80f8c806fb2edff354ee9c/content/overview/jwt-access-tokens.md#L51) .

**Comment by bshaffer** [comment]
the docs are incorrect, we represent scope as a [space-delimited format](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Scope.php#L48). Thanks for reporting this, I'll update the docs.
