### ISSUE TITLE
JWT Access Token Payload

### ISSUE THREAD

**Issue by 1leader** [bshaffer/oauth2-server-php-docs#70]
I would like to know if it is possible to add additional data to JWT Access Token Payload? For example we would like to include a user's role type in the JWT Access Token Payload. Thanks in advance!

**Comment by bshaffer** [comment]
Are you speaking particularly to JwtAccessTokens? If so, I think subclassing the [`createAccessToken`](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ResponseType/JwtAccessToken.php#L60) function would be the most straightforward way.

**Comment by 1leader** [comment]
Thanks so much this really helped!

Regards,




Javier Alvarez, Broker
Xcellence Realty, Inc
866-595-6025 x 210
