### ISSUE TITLE
Increase lifetime of Authorize code time

### ISSUE THREAD

**Issue by sajumani** [bshaffer/oauth2-server-php-docs#79]
Hi,'

how do we configure, Authorize code life time for 1 month...

**Comment by xastor** [comment]
I don't think that's a sensible thing to do.. authorization codes are meant to be used right away.  What's the usecase?

**Comment by bshaffer** [comment]
This is definitely too long of an expiration, but for others who come here with the same question, the way to do this is via the `auth_code_lifetime` config parameter:

```php
$config = ['auth_code_lifetime' => 10]; // make the code expire after 10 seconds
$server = new OAuth2\Server($storage, $config);
```
