### ISSUE TITLE
Cannot find the Step-by-Step Walkthrough page 

### ISSUE THREAD

**Issue by Jinny-Wang** [bshaffer/oauth2-server-php-docs#83]
I've been following the instructions on http://bshaffer.github.io/oauth2-server-php-docs/cookbook/  It worked very fine until this morning. When I tried to open it again to continue the setup of my server, I just got a "404 Not found" while other pages on the cookbook work well.
I just wonder if someone has renamed the page or temporarily moved it for modification. 
I'm kind of urgent in setting up my server. Hope this problem could be solved soon.

**Comment by bshaffer** [comment]
Thank you for finding this! This is fixed by b7dd0e8babd8425640232e80949406cbdd65e0d4 !

http://bshaffer.github.io/oauth2-server-php-docs/cookbook/

**Comment by Jinny-Wang** [comment]
Thank you so much for your in time reply!
