### ISSUE TITLE
issuing  JWT token without using pem

### ISSUE THREAD

**Issue by comeUpWithItLater** [bshaffer/oauth2-server-php-docs#88]
Any plan to add feature to issue JWT token without using pem?

**Comment by bshaffer** [comment]
Not at the moment. What format would you prefer?

**Comment by comeUpWithItLater** [comment]
My resource server  application is  written  in  C#/.net and need to parser token issued by  bshaffer's  oauth2-server-php , so I think JWT token without using *.pem would be great. I'm  not quite sure what format will do .

**Comment by bluebaroncanada** [comment]
Is this still an issue for you?

**Comment by comeUpWithItLater** [comment]
no.
time to close.
