### ISSUE TITLE
[Laravel] How can I change token expiration time?

### ISSUE THREAD

**Issue by gradosevic** [bshaffer/oauth2-server-php-docs#95]
I use this library and it's really great. The only problem that I have is that I want to extend default token expiration of one hour (3600). I don't see that any vendor configuration is deployed to Laravel's config folder. How can I do this? Thanks!

**Comment by bluebaroncanada** [comment]
This issue is for the actual code project and is already pending action.

**Comment by gradosevic** [comment]
This is what I needed

$config = array(
        'access_lifetime' => 86400
    );
    $server = new OAuth2\Server($storage, $config);
